### PR TITLE
[2.X] feat: add the support of the memory limit cli command of phpstan

### PR DESCRIPTION
**Pull request by Katalam**
When merge this PR will do
* add the support of the memory limit cli command of phpstan

It will set it with ini_set and checks with regex in front of the right format
PHPStan Variant: https://github.com/phpstan/phpstan-src/blob/5f96f504c509d02e65bdc20895dde5105df1a9b6/src/Command/CommandHelper.php#L114-L123

### CODE REVIEW

**Comment by JonPurvis** [comment]
Thanks for this @Katalam 🥳 

I noticed I'm also experiencing this, glad I'm not the only one. Hopefully this will be merged soon!

**Comment by JonPurvis** [comment]
@nunomaduro Apologies for the direct tag, any chance you could take a look at this PR please? A few folk are having to workaround the memory limit. I think the solution proposed in this PR is good and matches what PHPStan has!

Thanks!

**Comment by Saarnaki** [comment]
Can confirm that the given solution works

**Comment by ahtinurme** [comment]
Also having the same issue. Would be good to get this merged.

**Comment by Katalam** [comment]
I merged the base branch. So PR is ready to merge again

**Comment by ahtinurme** [comment]
Seems that the base tests are broken for the past 4 commits. I'll try to find time to create a PR to fix those as well.

**Comment by JonPurvis** [comment]
Thanks for your work on this @Katalam, can confirm it works wonderfully 👍 

Thanks to @nunomaduro for accepting the addition and merging! 🥳

**Pull request merged**
