### PR TITLE
Fix: Argument #20 ($polluteScopeWithBlock) must be of type bool error

### PR DESCRIPTION
**Pull request by MrPunyapal**
Based on [this](https://github.com/phpstan/phpstan-src/blob/2.0.x/src/Analyser/NodeScopeResolver.php#L258C3-L258C48) it accepts 25 arguments in the constructor but we are passing 28 (as per [1.x](https://github.com/phpstan/phpstan-src/blob/1.12.x/src/Analyser/NodeScopeResolver.php#L262)) right now. and the 20th argument is bool but we are passing an array. 

Therefore in this PR, I put true on the 20th argument and shifted other arguments +1 then removed arguments after the 25th argument same as a diff between [1.x](https://github.com/phpstan/phpstan-src/blob/1.12.x/src/Analyser/NodeScopeResolver.php#L262) and [2.x](https://github.com/phpstan/phpstan-src/blob/2.0.x/src/Analyser/NodeScopeResolver.php#L258C3-L258C48) PHPStan.

[this](https://github.com/MrPunyapal/basic-crud/actions/runs/12331578122/job/34418361358?pr=57) is not working and after these changes, it worked locally as expected you can see the screenshot below.
image

### CODE REVIEW

**Comment by owenvoke** [comment]
This looks good to me. We likely would have to drop support for PHPStan 1.x if we make this change though. 🤔

Unless we have some form of switch based on the PHPStan version, but then that might get kind of awkward to maintain.

**Comment by pushpak1300** [comment]
Screenshot 2024-12-21 at 6 10 30 PM
Can we please get this merged ?

**Comment by guille1988** [comment]
I have same problem too: 

Captura de pantalla 2024-12-21 a la(s) 17 35 47

**Comment by arnebr** [comment]
You can introduce this PR as a patch until the PR is merged. For that you need the composer patch package.
```shell
composer require cweagans/composer-patches:~2.0
```

Then you need to introduce this patch in the to be created patches.json
```json
{
    "patches": {
        "pestphp/pest-plugin-type-coverage": [
            {
                "description": "Fix: Argument #20 ($polluteScopeWithBlock) must be of type bool error ",
                "url": "https://github.com/pestphp/pest-plugin-type-coverage/pull/35.patch"
            }
        ]
    }
}
```

Then you need to make the patch to re-discover all available patches
```shell
composer patches-relock
```

Then we need to apply the patches. Icauses all patched dependencies to be deleted and re-installed, which causes patches to be re-applied to those dependencies. This command should be used when changing the list of patches in your project
```shell
composer patches-repatch
```

See [Composer Patches Documentation](https://docs.cweagans.net/composer-patches/usage/recommended-workflows/)

**Review by owenvoke — APPROVED** [review]
LGTM! Thanks! Apologies for this taking a while to merge.

Will do a patch release when I'm home.

**Comment by owenvoke** [comment]
This is now released as v3.2.2 👍🏻 Thanks for your work on it.

**Pull request merged**
